### ISSUE TITLE
Data errors

### ISSUE THREAD

**Issue by fre-sch** [fre-sch/collector-drone#32]
- Armour: All Recipes above level 1 missing.
- Shield Boosters: Blast/Kinetic/Thermal Resistant above level 3 missing.
- Distributor: Weapons/System/Engine Focused above level 3 missing.
- Hull Reinforcements: Lightweight level 1 added twice, Blast/Kinetic/Thermal Resistant above level 3 missing.
- FSD Interdictor: Category added twice, All Recipes above level 1 missing on the first, Longer Range modification missing on level 4 on the second.
- Lightweight alloy (armour) added as its own category.
- Power Plant: Low emission above level 3 missing.

**Comment by huehnerfaust** [comment]
hi there,

noticed a bug for the mine launcher light weight mount grade 3

There are Proto Alloys plus Proto Light Alloys listed, but only Proto Light Alloys are realy needed.

congrats to this fine webapp!

**Comment by fre-sch** [comment]
Blast Resistant Boosters: Neither the 'Elite Dangerous: Engineering Database & Calculator' nor 'Inara.cz' list any above grade 3, do these exist in game?
_I correct myself, they're listed on the EDEDC spreadsheet, but have no effect modifier values._

Kinetic Resistant Boosters: Neither the 'Elite Dangerous: Engineering Database & Calculator' nor 'Inara.cz' list any above grade 3, do these exist in game?
_I correct myself, they're listed on the EDEDC spreadsheet, but have no effect modifier values._

**Comment by fre-sch** [comment]
Thermal Resistant Boosters above grade 3 don't appear in the spreadsheet and inara either. Do they exist in game?

**Comment by fre-sch** [comment]
Longer Range FSD Interdictor above grade 3 not in spreadsheet and inara either, do they exist in game?

**Comment by fre-sch** [comment]
Low Emission Power Plant above grade 3 not in spreadsheet and inara, do they exist in game?

**Comment by fre-sch** [comment]
Weapons/System/Engine Focused Power Distributor above grade 3 not in spreadsheet and inara, do they exist in game?
