### ISSUE TITLE
Material rarity icons don't match ingame

### ISSUE THREAD

**Issue by huehnerfaust** [fre-sch/collector-drone#35]
i see that the icons that are beeing used come from edassets, but sadly they differ from the ingame ones. The common icon ingame has three "leaves" and in edassets three leaves stand for rare.

**Comment by fre-sch** [comment]
edassets.org and inara.cz both use the same (wrong) icons. Except for a few screenshots, I haven't found another online source to compare icons for rarities. Need to compare this in-game.
