### ISSUE TITLE
Blueprints screen shows some materials as Red when they should be Orange

### ISSUE THREAD

**Issue by maddavo** [fre-sch/collector-drone#37]
See picture at http://imgur.com/tr1lUEU
The pic shows a few blueprints.  Some materials have the required amounts satisfied but are still red.

**Comment by maddavo** [comment]
I found the steps to replicate.  The bug occurs when materials amounts are pre-existing and then a new blueprint is added to the tracker.  It seems the amounts are not checked when a blueprint the components just stay red.  If the amounts of a component changes, then that component is updated and changes colour if necessary OK.

**Comment by fre-sch** [comment]
@maddavo Just released 1.2, should be fixed now. Thanks a lot for your help!
